"_81f03589f5cecc73b8d08250347d979e.softwarepundit.com","HTTPSConnectionPool(host='_81f03589f5cecc73b8d08250347d979e.softwarepundit.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd053ae50>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"affiliate.softwarepundit.com","404 response"
"jslib.softwarepundit.com","404 response"
"jsonstudio.softwarepundit.com","401 response"
"mongogateway.softwarepundit.com","400 response"
"ssh.softwarepundit.com","HTTPSConnectionPool(host='ssh.softwarepundit.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd053ae80>, 'Connection to ssh.softwarepundit.com timed out. (connect timeout=10)'))"
"\052.crm-software-application.com","HTTPSConnectionPool(host='%5c052.crm-software-application.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04c62b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"_bf12f3c354944766c4874243a2f96a0b.crm-software-application.com","HTTPSConnectionPool(host='_bf12f3c354944766c4874243a2f96a0b.crm-software-application.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04c6460>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"\052.careersinhouston.com","HTTPSConnectionPool(host='%5c052.careersinhouston.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04c63d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"_4e5cd896efabae21053b7e908ea1a70d.careersinhouston.com","HTTPSConnectionPool(host='_4e5cd896efabae21053b7e908ea1a70d.careersinhouston.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04c6220>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"\052.famundo.com","HTTPSConnectionPool(host='%5c052.famundo.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04c6910>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"_29c7bfddad3e7412de09d1d49a29fb9e.famundo.com","HTTPSConnectionPool(host='_29c7bfddad3e7412de09d1d49a29fb9e.famundo.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04c6460>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"\052.pmhut.com","HTTPSConnectionPool(host='%5c052.pmhut.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04c6490>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"itv62454hqwou556daykge3fczd34nxb._domainkey.pmhut.com","HTTPSConnectionPool(host='itv62454hqwou556daykge3fczd34nxb._domainkey.pmhut.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04c6a90>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"n44insibijiw3ezfkiptn4vrqgbjiupi._domainkey.pmhut.com","HTTPSConnectionPool(host='n44insibijiw3ezfkiptn4vrqgbjiupi._domainkey.pmhut.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04c6250>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"sygyzzmek63bgraougsbb3w3kpfqb74u._domainkey.pmhut.com","HTTPSConnectionPool(host='sygyzzmek63bgraougsbb3w3kpfqb74u._domainkey.pmhut.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04c69d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"\052.curioso.org","HTTPSConnectionPool(host='%5c052.curioso.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04c6fa0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"_47219916b64413c0fad19f234f20cedf.curioso.org","HTTPSConnectionPool(host='_47219916b64413c0fad19f234f20cedf.curioso.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04c6100>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"\052.dabbledb.com","HTTPSConnectionPool(host='%5c052.dabbledb.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04c6910>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"_9e7ea179e20fefba9354c90902e5539f.dabbledb.com","HTTPSConnectionPool(host='_9e7ea179e20fefba9354c90902e5539f.dabbledb.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04c6250>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"\052.inventiondb.com","HTTPSConnectionPool(host='%5c052.inventiondb.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04c6400>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"_cfb04da09558d099dab7ddba6efc575f.inventiondb.com","HTTPSConnectionPool(host='_cfb04da09558d099dab7ddba6efc575f.inventiondb.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04c6040>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"\052.project-management-center.com","HTTPSConnectionPool(host='%5c052.project-management-center.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04c6a60>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"_42c1a3fb8a94e54e301f539ec2d77762.project-management-center.com","HTTPSConnectionPool(host='_42c1a3fb8a94e54e301f539ec2d77762.project-management-center.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04c6f70>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"isolsoft.com","HTTPSConnectionPool(host='isolsoft.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04c69d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))"
"\052.isolsoft.com","HTTPSConnectionPool(host='%5c052.isolsoft.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04c6100>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"_2d9302cc72be05a9da165597fd9c7aba.isolsoft.com","HTTPSConnectionPool(host='_2d9302cc72be05a9da165597fd9c7aba.isolsoft.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04c6040>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))"
"\052.pm-sherpa.com","HTTPSConnectionPool(host='%5c052.pm-sherpa.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04c6490>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"_61a679a23b5b9bf8f4b76322a7dca3f5.pm-sherpa.com","HTTPSConnectionPool(host='_61a679a23b5b9bf8f4b76322a7dca3f5.pm-sherpa.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04c6070>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"\052.pm411.org","HTTPSConnectionPool(host='%5c052.pm411.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04c6f40>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"_cec195bcac122f47fcf9ff3185ebfe67.pm411.org","HTTPSConnectionPool(host='_cec195bcac122f47fcf9ff3185ebfe67.pm411.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04c6910>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"\052.project-management-software.com","HTTPSConnectionPool(host='%5c052.project-management-software.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04c6a60>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"\052.project-management-software.org","HTTPSConnectionPool(host='%5c052.project-management-software.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04c6ca0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"34404865.project-management.com","404 response"
"\052.project-management.com","HTTPSConnectionPool(host='%5c052.project-management.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04c63d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"cmkaculgrx5edw7kzq2vymv3swwucgyh._domainkey.project-management.com","HTTPSConnectionPool(host='cmkaculgrx5edw7kzq2vymv3swwucgyh._domainkey.project-management.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04c6e20>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"gdu45larsuoxbcxwmz74npdr4d4jhzb6._domainkey.project-management.com","HTTPSConnectionPool(host='gdu45larsuoxbcxwmz74npdr4d4jhzb6._domainkey.project-management.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04c6340>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"nuryqmprmy2qsr6cyqqrxeb3rcnuliq3._domainkey.project-management.com","HTTPSConnectionPool(host='nuryqmprmy2qsr6cyqqrxeb3rcnuliq3._domainkey.project-management.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04c63d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"checkup-test.project-management.com","404 response"
"local.project-management.com","HTTPSConnectionPool(host='local.project-management.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04c63d0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"mail.project-management.com","HTTPSConnectionPool(host='mail.project-management.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))"
"smtp.project-management.com","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
"test-pmcom.project-management.com","Exceeded 30 redirects."
"\052.project-management.org","HTTPSConnectionPool(host='%5c052.project-management.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04de700>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"\052.project-management-tools.net","HTTPSConnectionPool(host='%5c052.project-management-tools.net', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd053a6a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"\052.projectmgt.com","HTTPSConnectionPool(host='%5c052.projectmgt.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04c6fa0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"\052.theinternationalpm.com","HTTPSConnectionPool(host='%5c052.theinternationalpm.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd053a910>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"\052.whybasecampsux.org","HTTPSConnectionPool(host='%5c052.whybasecampsux.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04de790>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"\052.schemequest.com","HTTPSConnectionPool(host='%5c052.schemequest.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04241f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"\052.ravensbrain.com","HTTPSConnectionPool(host='%5c052.ravensbrain.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd049bee0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"\052.projectmagazine.com","HTTPSConnectionPool(host='%5c052.projectmagazine.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04245b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"\052.skrubcrm.com","HTTPSConnectionPool(host='%5c052.skrubcrm.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0424a90>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"\052.tuggo.org","HTTPSConnectionPool(host='%5c052.tuggo.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd049bca0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"\052.web-based-software.com","HTTPSConnectionPool(host='%5c052.web-based-software.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04ce670>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"_c5b657c4481e3a134bd2766821f36e62.relay.cool","HTTPSConnectionPool(host='_c5b657c4481e3a134bd2766821f36e62.relay.cool', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04ce550>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"_ecbb4747b9202f6c51ad262cb8959309.concourse.relay.cool","HTTPSConnectionPool(host='_ecbb4747b9202f6c51ad262cb8959309.concourse.relay.cool', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04cebb0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"gateway.concourse.relay.cool","HTTPSConnectionPool(host='gateway.concourse.relay.cool', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04cea90>, 'Connection to gateway.concourse.relay.cool timed out. (connect timeout=10)'))"
"dashboard.relay.cool","404 response"
"_bd493080440b6b0c3fee7a7e9e7e18b6.dashboard.relay.cool","HTTPSConnectionPool(host='_bd493080440b6b0c3fee7a7e9e7e18b6.dashboard.relay.cool', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0424fd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"dev.dashboard.relay.cool","404 response"
"_36d227a87978813d5e7c8d5b9cfa2df7.dev.dashboard.relay.cool","HTTPSConnectionPool(host='_36d227a87978813d5e7c8d5b9cfa2df7.dev.dashboard.relay.cool', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04244f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"db-gateway.relay.cool","HTTPSConnectionPool(host='db-gateway.relay.cool', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04248b0>, 'Connection to db-gateway.relay.cool timed out. (connect timeout=10)'))"
"dev.db-gateway.relay.cool","HTTPSConnectionPool(host='dev.db-gateway.relay.cool', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04de8e0>, 'Connection to dev.db-gateway.relay.cool timed out. (connect timeout=10)'))"
"goldmine-read-only.db.relay.cool","HTTPSConnectionPool(host='goldmine-read-only.db.relay.cool', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd042d940>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"goldmine.db.relay.cool","HTTPSConnectionPool(host='goldmine.db.relay.cool', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd042da00>: Failed to establish a new connection: [Errno 113] No route to host'))"
"_227294c1cd462b939c1c762cefc0ddea.dev.relay.cool","HTTPSConnectionPool(host='_227294c1cd462b939c1c762cefc0ddea.dev.relay.cool', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043a1f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"_b4cf730aed3acb1f1720080186d7d143.dev.docs.relay.cool","HTTPSConnectionPool(host='_b4cf730aed3acb1f1720080186d7d143.dev.docs.relay.cool', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043a370>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"dev.forums.justlinux.forums.relay.cool","HTTPSConnectionPool(host='dev.forums.justlinux.forums.relay.cool', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043a3a0>, 'Connection to dev.forums.justlinux.forums.relay.cool timed out. (connect timeout=10)'))"
"dev.www.sharkyforums.forums.relay.cool","HTTPSConnectionPool(host='dev.www.sharkyforums.forums.relay.cool', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd042da60>, 'Connection to dev.www.sharkyforums.forums.relay.cool timed out. (connect timeout=10)'))"
"dev.discussions.virtualdr.forums.relay.cool","HTTPSConnectionPool(host='dev.discussions.virtualdr.forums.relay.cool', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04de310>, 'Connection to dev.discussions.virtualdr.forums.relay.cool timed out. (connect timeout=10)'))"
"dev.www.windrivers.forums.relay.cool","HTTPSConnectionPool(host='dev.www.windrivers.forums.relay.cool', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04cebb0>, 'Connection to dev.www.windrivers.forums.relay.cool timed out. (connect timeout=10)'))"
"ftp.relay.cool","HTTPSConnectionPool(host='ftp.relay.cool', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd053a400>, 'Connection to ftp.relay.cool timed out. (connect timeout=10)'))"
"gateway.relay.cool","HTTPSConnectionPool(host='gateway.relay.cool', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd049bbe0>, 'Connection to gateway.relay.cool timed out. (connect timeout=10)'))"
"dev.gateway.relay.cool","HTTPSConnectionPool(host='dev.gateway.relay.cool', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0424130>, 'Connection to dev.gateway.relay.cool timed out. (connect timeout=10)'))"
"prod.gateway.relay.cool","HTTPSConnectionPool(host='prod.gateway.relay.cool', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0424460>, 'Connection to prod.gateway.relay.cool timed out. (connect timeout=10)'))"
"_3b67fc7c85a10216c3edd1962c7c0817.goldmine-scheduler.relay.cool","HTTPSConnectionPool(host='_3b67fc7c85a10216c3edd1962c7c0817.goldmine-scheduler.relay.cool', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd053ae80>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"_592f567069dabc934f9f7174f24d1f36.dev.goldmine-scheduler.relay.cool","HTTPSConnectionPool(host='_592f567069dabc934f9f7174f24d1f36.dev.goldmine-scheduler.relay.cool', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd049b5e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"_552af7f3069b77925de110215e4643ab.old.goldmine-scheduler.relay.cool","HTTPSConnectionPool(host='_552af7f3069b77925de110215e4643ab.old.goldmine-scheduler.relay.cool', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04de280>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"lexisnexis.relay.cool","HTTPSConnectionPool(host='lexisnexis.relay.cool', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd049b730>, 'Connection to lexisnexis.relay.cool timed out. (connect timeout=10)'))"
"_fa191b738af8d643facfe4130742d98b.ml-tool.relay.cool","HTTPSConnectionPool(host='_fa191b738af8d643facfe4130742d98b.ml-tool.relay.cool', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04c69d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"_a42524625200f6a93262eb1fbb7bb240.serverwatch.relay.cool","HTTPSConnectionPool(host='_a42524625200f6a93262eb1fbb7bb240.serverwatch.relay.cool', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04c6460>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"_f04cf33f649235de6e40570dfb9d1a33.sonarqube.relay.cool","HTTPSConnectionPool(host='_f04cf33f649235de6e40570dfb9d1a33.sonarqube.relay.cool', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04cedf0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"_25fa0eed52f3f8273bab7ae73a191263.superset.relay.cool","HTTPSConnectionPool(host='_25fa0eed52f3f8273bab7ae73a191263.superset.relay.cool', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04c6910>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"gateway.superset.relay.cool","HTTPSConnectionPool(host='gateway.superset.relay.cool', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04c62e0>, 'Connection to gateway.superset.relay.cool timed out. (connect timeout=10)'))"
"westlaw.relay.cool","HTTPSConnectionPool(host='westlaw.relay.cool', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0431a90>, 'Connection to westlaw.relay.cool timed out. (connect timeout=10)'))"
"www.relay.cool","500 response"
"_02b740b5b2b53dc27b72a1c1004fe55f.dev.xenforo.relay.cool","HTTPSConnectionPool(host='_02b740b5b2b53dc27b72a1c1004fe55f.dev.xenforo.relay.cool', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04314c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"34406656.dbasupport.com","404 response"
"_a3578f93ce3c3f41ca3b0564db059bee.dbasupport.com","HTTPSConnectionPool(host='_a3578f93ce3c3f41ca3b0564db059bee.dbasupport.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0431f40>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"assetform.dbasupport.com","HTTPSConnectionPool(host='assetform.dbasupport.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0431e80>, 'Connection to assetform.dbasupport.com timed out. (connect timeout=10)'))"
"forums.dbasupport.com","HTTPSConnectionPool(host='forums.dbasupport.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04314c0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"ora.dbasupport.com","HTTPSConnectionPool(host='ora.dbasupport.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd052a850>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"sql.dbasupport.com","HTTPSConnectionPool(host='sql.dbasupport.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04de2e0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"dev.www.dbasupport.com","HTTPSConnectionPool(host='dev.www.dbasupport.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0440f40>, 'Connection to dev.www.dbasupport.com timed out. (connect timeout=10)'))"
"prod.www.dbasupport.com","HTTPSConnectionPool(host='prod.www.dbasupport.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd044bee0>, 'Connection to prod.www.dbasupport.com timed out. (connect timeout=10)'))"
"34266668.eweek.com","404 response"
"assetform.eweek.com","HTTPSConnectionPool(host='assetform.eweek.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04406a0>, 'Connection to assetform.eweek.com timed out. (connect timeout=10)'))"
"blog.eweek.com","HTTPSConnectionPool(host='blog.eweek.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04de790>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"blogs.eweek.com","HTTPSConnectionPool(host='blogs.eweek.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04c6d90>, 'Connection to blogs.eweek.com timed out. (connect timeout=10)'))"
"bounce1.eweek.com","HTTPSConnectionPool(host='bounce1.eweek.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0431af0>, 'Connection to bounce1.eweek.com timed out. (connect timeout=10)'))"
"bounce2.eweek.com","HTTPSConnectionPool(host='bounce2.eweek.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04319d0>, 'Connection to bounce2.eweek.com timed out. (connect timeout=10)'))"
"bounce3.eweek.com","HTTPSConnectionPool(host='bounce3.eweek.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0438730>, 'Connection to bounce3.eweek.com timed out. (connect timeout=10)'))"
"buyersguide.eweek.com","HTTPSConnectionPool(host='buyersguide.eweek.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043a1f0>, 'Connection to buyersguide.eweek.com timed out. (connect timeout=10)'))"
"careers.eweek.com","HTTPSConnectionPool(host='careers.eweek.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0438940>, 'Connection to careers.eweek.com timed out. (connect timeout=10)'))"
"www.careers.eweek.com","HTTPSConnectionPool(host='www.careers.eweek.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0431c70>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"collaboration.eweek.com","HTTPSConnectionPool(host='collaboration.eweek.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0431a30>, 'Connection to collaboration.eweek.com timed out. (connect timeout=10)'))"
"confirmations.eweek.com","HTTPSConnectionPool(host='confirmations.eweek.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd053a8b0>, 'Connection to confirmations.eweek.com timed out. (connect timeout=10)'))"
"ct.eweek.com","HTTPSConnectionPool(host='ct.eweek.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04de040>, 'Connection to ct.eweek.com timed out. (connect timeout=10)'))"
"database.eweek.com","HTTPSConnectionPool(host='database.eweek.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd042dfd0>, 'Connection to database.eweek.com timed out. (connect timeout=10)'))"
"desktop.eweek.com","HTTPSConnectionPool(host='desktop.eweek.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd044bee0>, 'Connection to desktop.eweek.com timed out. (connect timeout=10)'))"
"dev-resources.eweek.com","HTTPSConnectionPool(host='dev-resources.eweek.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043a190>, 'Connection to dev-resources.eweek.com timed out. (connect timeout=10)'))"
"dev.eweek.com","HTTPSConnectionPool(host='dev.eweek.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd044bac0>, 'Connection to dev.eweek.com timed out. (connect timeout=10)'))"
"developer.eweek.com","HTTPSConnectionPool(host='developer.eweek.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd042d970>, 'Connection to developer.eweek.com timed out. (connect timeout=10)'))"
"digital.eweek.com","HTTPSConnectionPool(host='digital.eweek.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04ce610>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"discuss.eweek.com","HTTPSConnectionPool(host='discuss.eweek.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd053a850>, 'Connection to discuss.eweek.com timed out. (connect timeout=10)'))"
"eletters.eweek.com","HTTPSConnectionPool(host='eletters.eweek.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04317f0>, 'Connection to eletters.eweek.com timed out. (connect timeout=10)'))"
"emergingtechnologies.eweek.com","HTTPSConnectionPool(host='emergingtechnologies.eweek.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0431b20>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"emergingtechnology.eweek.com","HTTPSConnectionPool(host='emergingtechnology.eweek.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043a790>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"enterpriseapps.eweek.com","HTTPSConnectionPool(host='enterpriseapps.eweek.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0438d00>, 'Connection to enterpriseapps.eweek.com timed out. (connect timeout=10)'))"
"esp.eweek.com","HTTPSConnectionPool(host='esp.eweek.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0431610>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"leads.esp.eweek.com","HTTPSConnectionPool(host='leads.esp.eweek.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04c6fa0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"www.esp.eweek.com","HTTPSConnectionPool(host='www.esp.eweek.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04de550>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"etech.eweek.com","HTTPSConnectionPool(host='etech.eweek.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd042d130>, 'Connection to etech.eweek.com timed out. (connect timeout=10)'))"
"eweekdigital.eweek.com","HTTPSConnectionPool(host='eweekdigital.eweek.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043a040>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"ezp.eweek.com","HTTPSConnectionPool(host='ezp.eweek.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd044bfd0>, 'Connection to ezp.eweek.com timed out. (connect timeout=10)'))"
"finance.eweek.com","HTTPSConnectionPool(host='finance.eweek.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04386d0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"www.go.eweek.com","HTTPSConnectionPool(host='www.go.eweek.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0440340>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"googlewatch.eweek.com","HTTPSConnectionPool(host='googlewatch.eweek.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0431d00>, 'Connection to googlewatch.eweek.com timed out. (connect timeout=10)'))"
"www.googlewatch.eweek.com","HTTPSConnectionPool(host='www.googlewatch.eweek.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0431eb0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"health.eweek.com","HTTPSConnectionPool(host='health.eweek.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043ad00>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"ibmwatch.eweek.com","HTTPSConnectionPool(host='ibmwatch.eweek.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043aa60>, 'Connection to ibmwatch.eweek.com timed out. (connect timeout=10)'))"
"infrastructure.eweek.com","HTTPSConnectionPool(host='infrastructure.eweek.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043aac0>, 'Connection to infrastructure.eweek.com timed out. (connect timeout=10)'))"
"internetinfrastructurecenter.eweek.com","HTTPSConnectionPool(host='internetinfrastructurecenter.eweek.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd052a850>, 'Connection to internetinfrastructurecenter.eweek.com timed out. (connect timeout=10)'))"
"interviews.eweek.com","HTTPSConnectionPool(host='interviews.eweek.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04318e0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"katt.eweek.com","HTTPSConnectionPool(host='katt.eweek.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd053afa0>, 'Connection to katt.eweek.com timed out. (connect timeout=10)'))"
"labs.eweek.com","HTTPSConnectionPool(host='labs.eweek.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd044b9a0>, 'Connection to labs.eweek.com timed out. (connect timeout=10)'))"
"li.eweek.com","404 response"
"linux.eweek.com","HTTPSConnectionPool(host='linux.eweek.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04ce250>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"linuxworld.eweek.com","HTTPSConnectionPool(host='linuxworld.eweek.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043deb0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"m.eweek.com","HTTPSConnectionPool(host='m.eweek.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043d3d0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"www.m.eweek.com","HTTPSConnectionPool(host='www.m.eweek.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04408e0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"macintosh.eweek.com","HTTPSConnectionPool(host='macintosh.eweek.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043ecd0>, 'Connection to macintosh.eweek.com timed out. (connect timeout=10)'))"
"manufacturing.eweek.com","HTTPSConnectionPool(host='manufacturing.eweek.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04389d0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"media.eweek.com","HTTPSConnectionPool(host='media.eweek.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0438040>, 'Connection to media.eweek.com timed out. (connect timeout=10)'))"
"media1.eweek.com","HTTPSConnectionPool(host='media1.eweek.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0431ac0>, 'Connection to media1.eweek.com timed out. (connect timeout=10)'))"
"media2.eweek.com","HTTPSConnectionPool(host='media2.eweek.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0431fd0>, 'Connection to media2.eweek.com timed out. (connect timeout=10)'))"
"mediakits.eweek.com","HTTPSConnectionPool(host='mediakits.eweek.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043aa30>, 'Connection to mediakits.eweek.com timed out. (connect timeout=10)'))"
"messaging.eweek.com","HTTPSConnectionPool(host='messaging.eweek.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043af40>, 'Connection to messaging.eweek.com timed out. (connect timeout=10)'))"
"midmarket.eweek.com","HTTPSConnectionPool(host='midmarket.eweek.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0431a60>, 'Connection to midmarket.eweek.com timed out. (connect timeout=10)'))"
"www.midmarket.eweek.com","HTTPSConnectionPool(host='www.midmarket.eweek.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0438340>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"www.mobile.eweek.com","400 response"
"mobiledevices.eweek.com","HTTPSConnectionPool(host='mobiledevices.eweek.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0438d90>, 'Connection to mobiledevices.eweek.com timed out. (connect timeout=10)'))"
"networkcommunity.eweek.com","HTTPSConnectionPool(host='networkcommunity.eweek.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043e820>, 'Connection to networkcommunity.eweek.com timed out. (connect timeout=10)'))"
"networking.eweek.com","HTTPSConnectionPool(host='networking.eweek.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0440970>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"www.networking.eweek.com","HTTPSConnectionPool(host='www.networking.eweek.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043abb0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"networkingcommunityconnection.eweek.com","HTTPSConnectionPool(host='networkingcommunityconnection.eweek.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043aa00>, 'Connection to networkingcommunityconnection.eweek.com timed out. (connect timeout=10)'))"
"news.eweek.com","HTTPSConnectionPool(host='news.eweek.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd044baf0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"onswipe.eweek.com","HTTPSConnectionPool(host='onswipe.eweek.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0440c70>, 'Connection to onswipe.eweek.com timed out. (connect timeout=10)'))"
"origin321-mobile.eweek.com","HTTPSConnectionPool(host='origin321-mobile.eweek.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0440a30>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"origin321-sponsored.eweek.com","HTTPSConnectionPool(host='origin321-sponsored.eweek.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043ef10>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"origin321-www.eweek.com","HTTPSConnectionPool(host='origin321-www.eweek.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0438d30>, 'Connection to origin321-www.eweek.com timed out. (connect timeout=10)'))"
"p5ok5mwnu7wb.eweek.com","HTTPSConnectionPool(host='p5ok5mwnu7wb.eweek.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04312e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"preview.eweek.com","HTTPSConnectionPool(host='preview.eweek.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04317c0>, 'Connection to preview.eweek.com timed out. (connect timeout=10)'))"
"www.renew.eweek.com","HTTPSConnectionPool(host='www.renew.eweek.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0431130>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"research.eweek.com","HTTPSConnectionPool(host='research.eweek.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd044bd30>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"resources.eweek.com","HTTPSConnectionPool(host='resources.eweek.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04310d0>, 'Connection to resources.eweek.com timed out. (connect timeout=10)'))"
"response.eweek.com","HTTPSConnectionPool(host='response.eweek.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0438d00>, 'Connection to response.eweek.com timed out. (connect timeout=10)'))"
"zdmta.response.eweek.com","HTTPSConnectionPool(host='zdmta.response.eweek.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043e9d0>, 'Connection to zdmta.response.eweek.com timed out. (connect timeout=10)'))"
"retail.eweek.com","HTTPSConnectionPool(host='retail.eweek.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043e100>, 'Connection to retail.eweek.com timed out. (connect timeout=10)'))"
"reviews.eweek.com","HTTPSConnectionPool(host='reviews.eweek.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04405e0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"security.eweek.com","HTTPSConnectionPool(host='security.eweek.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043a3d0>, 'Connection to security.eweek.com timed out. (connect timeout=10)'))"
"securitywatch.eweek.com","HTTPSConnectionPool(host='securitywatch.eweek.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd044b520>, 'Connection to securitywatch.eweek.com timed out. (connect timeout=10)'))"
"www.securitywatch.eweek.com","HTTPSConnectionPool(host='www.securitywatch.eweek.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd044b130>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"servers.eweek.com","HTTPSConnectionPool(host='servers.eweek.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04406d0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"simplifypcsolutions.eweek.com","HTTPSConnectionPool(host='simplifypcsolutions.eweek.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0440a30>, 'Connection to simplifypcsolutions.eweek.com timed out. (connect timeout=10)'))"
"smallbusinesszone.eweek.com","HTTPSConnectionPool(host='smallbusinesszone.eweek.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043e160>, 'Connection to smallbusinesszone.eweek.com timed out. (connect timeout=10)'))"
"smartercloudinfrastructure.eweek.com","HTTPSConnectionPool(host='smartercloudinfrastructure.eweek.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04388b0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"www.smartercloudinfrastructure.eweek.com","HTTPSConnectionPool(host='www.smartercloudinfrastructure.eweek.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04380a0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"solutions.eweek.com","HTTPSConnectionPool(host='solutions.eweek.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0431040>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"spk.eweek.com","HTTPSConnectionPool(host='spk.eweek.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd053a850>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"sponsored.eweek.com","HTTPSConnectionPool(host='sponsored.eweek.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd053aa30>, 'Connection to sponsored.eweek.com timed out. (connect timeout=10)'))"
"storage.eweek.com","HTTPSConnectionPool(host='storage.eweek.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0431e20>, 'Connection to storage.eweek.com timed out. (connect timeout=10)'))"
"subscribe.eweek.com","HTTPSConnectionPool(host='subscribe.eweek.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0438760>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"t.eweek.com","HTTPSConnectionPool(host='t.eweek.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0438040>, 'Connection to t.eweek.com timed out. (connect timeout=10)'))"
"telephony.eweek.com","HTTPSConnectionPool(host='telephony.eweek.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043e580>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"test.eweek.com","403 response"
"tools.eweek.com","HTTPSConnectionPool(host='tools.eweek.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0440a60>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"upfront.eweek.com","HTTPSConnectionPool(host='upfront.eweek.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043a2e0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"voip.eweek.com","HTTPSConnectionPool(host='voip.eweek.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd053a8b0>, 'Connection to voip.eweek.com timed out. (connect timeout=10)'))"
"web.eweek.com","HTTPSConnectionPool(host='web.eweek.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd044bf40>, 'Connection to web.eweek.com timed out. (connect timeout=10)'))"
"web1.eweek.com","HTTPSConnectionPool(host='web1.eweek.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0440700>, 'Connection to web1.eweek.com timed out. (connect timeout=10)'))"
"web2.eweek.com","HTTPSConnectionPool(host='web2.eweek.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043ed30>, 'Connection to web2.eweek.com timed out. (connect timeout=10)'))"
"white-papers.eweek.com","HTTPSConnectionPool(host='white-papers.eweek.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0438340>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"whitepapers.eweek.com","HTTPSConnectionPool(host='whitepapers.eweek.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04385b0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"windows.eweek.com","HTTPSConnectionPool(host='windows.eweek.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04318e0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"wireless.eweek.com","HTTPSConnectionPool(host='wireless.eweek.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0431fd0>, 'Connection to wireless.eweek.com timed out. (connect timeout=10)'))"
"ww2.eweek.com","404 response"
"_dc8a48861839f40faa8080c433931e3b.www.eweek.com","HTTPSConnectionPool(host='_dc8a48861839f40faa8080c433931e3b.www.eweek.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0431070>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"34460951.developer.com","404 response"
"amazon.developer.com","403 response"
"android.developer.com","403 response"
"apple.developer.com","403 response"
"assetform.developer.com","HTTPSConnectionPool(host='assetform.developer.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0431520>, 'Connection to assetform.developer.com timed out. (connect timeout=10)'))"
"assets.developer.com","HTTPSConnectionPool(host='www.assets.developer.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04310d0>, 'Connection to www.assets.developer.com timed out. (connect timeout=10)'))"
"bi-systems.developer.com","HTTPSConnectionPool(host='bi-systems.developer.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0438070>, 'Connection to bi-systems.developer.com timed out. (connect timeout=10)'))"
"bounce1.developer.com","HTTPSConnectionPool(host='bounce1.developer.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0438c70>, 'Connection to bounce1.developer.com timed out. (connect timeout=10)'))"
"courses.developer.com","HTTPSConnectionPool(host='courses.developer.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043e220>, 'Connection to courses.developer.com timed out. (connect timeout=10)'))"
"ct.developer.com","HTTPSConnectionPool(host='ct.developer.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043e460>, 'Connection to ct.developer.com timed out. (connect timeout=10)'))"
"dbms.developer.com","HTTPSConnectionPool(host='dbms.developer.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04405e0>, 'Connection to dbms.developer.com timed out. (connect timeout=10)'))"
"dev-www.developer.com","HTTPSConnectionPool(host='dev-www.developer.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043a460>, 'Connection to dev-www.developer.com timed out. (connect timeout=10)'))"
"devchannel.developer.com","HTTPSConnectionPool(host='devchannel.developer.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04c6340>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"facebook.developer.com","403 response"
"google.developer.com","403 response"
"google830cfe34123799dd.developer.com","404 response"
"ides.developer.com","HTTPSConnectionPool(host='ides.developer.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0440a30>, 'Connection to ides.developer.com timed out. (connect timeout=10)'))"
"intranetjournal.developer.com","HTTPSConnectionPool(host='intranetjournal.developer.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))"
"li.developer.com","404 response"
"origin321-www.developer.com","400 response"
"resources.developer.com","HTTPSConnectionPool(host='resources.developer.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0438f70>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"solutions.developer.com","HTTPSConnectionPool(host='solutions.developer.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0438490>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"sp.developer.com","400 response"
"text-editors.developer.com","HTTPSConnectionPool(host='text-editors.developer.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043e4f0>, 'Connection to text-editors.developer.com timed out. (connect timeout=10)'))"
"videos.developer.com","HTTPSConnectionPool(host='videos.developer.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd044b250>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"windows.developer.com","403 response"
"ww2.developer.com","404 response"
"34406691.4guysfromrolla.com","404 response"
"aspnet.4guysfromrolla.com","HTTPSConnectionPool(host='aspnet.4guysfromrolla.com', port=443): Read timed out. (read timeout=10)"
"assetform.4guysfromrolla.com","HTTPSConnectionPool(host='assetform.4guysfromrolla.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0438bb0>, 'Connection to assetform.4guysfromrolla.com timed out. (connect timeout=10)'))"
"ftp.4guysfromrolla.com","HTTPSConnectionPool(host='ftp.4guysfromrolla.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04385b0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"ww2.4guysfromrolla.com","404 response"
"34404860.cioinsight.com","404 response"
"assetform.cioinsight.com","HTTPSConnectionPool(host='assetform.cioinsight.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04400d0>, 'Connection to assetform.cioinsight.com timed out. (connect timeout=10)'))"
"blog.cioinsight.com","HTTPSConnectionPool(host='blog.cioinsight.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043a760>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"blogs.cioinsight.com","HTTPSConnectionPool(host='www.blogs.cioinsight.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0431eb0>, 'Connection to www.blogs.cioinsight.com timed out. (connect timeout=10)'))"
"buyersguide.cioinsight.com","HTTPSConnectionPool(host='buyersguide.cioinsight.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043a850>, 'Connection to buyersguide.cioinsight.com timed out. (connect timeout=10)'))"
"cioinsightdigital.cioinsight.com","HTTPSConnectionPool(host='cioinsightdigital.cioinsight.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0440ee0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"confirmations.cioinsight.com","HTTPSConnectionPool(host='confirmations.cioinsight.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04388b0>, 'Connection to confirmations.cioinsight.com timed out. (connect timeout=10)'))"
"ct.cioinsight.com","HTTPSConnectionPool(host='ct.cioinsight.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04381f0>, 'Connection to ct.cioinsight.com timed out. (connect timeout=10)'))"
"digital.cioinsight.com","HTTPSConnectionPool(host='digital.cioinsight.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043e8e0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"go.cioinsight.com","HTTPSConnectionPool(host='go.cioinsight.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043e3d0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"it-jobs.cioinsight.com","HTTPSConnectionPool(host='it-jobs.cioinsight.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd044b190>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"m.cioinsight.com","403 response"
"www.m.cioinsight.com","HTTPSConnectionPool(host='www.m.cioinsight.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043eaf0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"www.mobile.cioinsight.com","HTTPSConnectionPool(host='www.mobile.cioinsight.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04c6eb0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"mobilenew.cioinsight.com","HTTPSConnectionPool(host='mobilenew.cioinsight.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0438040>, 'Connection to mobilenew.cioinsight.com timed out. (connect timeout=10)'))"
"origin321-blogs.cioinsight.com","HTTPSConnectionPool(host='origin321-blogs.cioinsight.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0438850>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"origin321-mobile.cioinsight.com","HTTPSConnectionPool(host='origin321-mobile.cioinsight.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0440df0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"origin321-www.cioinsight.com","HTTPSConnectionPool(host='origin321-www.cioinsight.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043aa00>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"response.cioinsight.com","HTTPSConnectionPool(host='response.cioinsight.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd053afd0>, 'Connection to response.cioinsight.com timed out. (connect timeout=10)'))"
"subscribe.cioinsight.com","HTTPSConnectionPool(host='subscribe.cioinsight.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0440cd0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"t.cioinsight.com","HTTPSConnectionPool(host='t.cioinsight.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0440f10>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"ww2.cioinsight.com","404 response"
"34419446.itbusinessedge.com","404 response"
"archives.itbusinessedge.com","HTTPSConnectionPool(host='archives.itbusinessedge.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0438d30>, 'Connection to archives.itbusinessedge.com timed out. (connect timeout=10)'))"
"assetform.itbusinessedge.com","HTTPSConnectionPool(host='assetform.itbusinessedge.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043e4f0>, 'Connection to assetform.itbusinessedge.com timed out. (connect timeout=10)'))"
"autodiscover.itbusinessedge.com","HTTPSConnectionPool(host='autodiscover.itbusinessedge.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043ef10>, 'Connection to autodiscover.itbusinessedge.com timed out. (connect timeout=10)'))"
"bp.itbusinessedge.com","HTTPSConnectionPool(host='bp.itbusinessedge.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd044b040>, 'Connection to bp.itbusinessedge.com timed out. (connect timeout=10)'))"
"mail.bp.itbusinessedge.com","HTTPSConnectionPool(host='mail.bp.itbusinessedge.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043ac70>, 'Connection to mail.bp.itbusinessedge.com timed out. (connect timeout=10)'))"
"ct.itbusinessedge.com","HTTPSConnectionPool(host='ct.itbusinessedge.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd044b040>, 'Connection to ct.itbusinessedge.com timed out. (connect timeout=10)'))"
"dl.itbusinessedge.com","HTTPSConnectionPool(host='dl.itbusinessedge.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043e8e0>, 'Connection to dl.itbusinessedge.com timed out. (connect timeout=10)'))"
"e-newsletters.itbusinessedge.com","HTTPSConnectionPool(host='e-newsletters.itbusinessedge.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04c6520>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"eduebooks.itbusinessedge.com","HTTPSConnectionPool(host='eduebooks.itbusinessedge.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04388e0>, 'Connection to eduebooks.itbusinessedge.com timed out. (connect timeout=10)'))"
"freelancer.itbusinessedge.com","HTTPSConnectionPool(host='freelancer.itbusinessedge.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0438280>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"jobs.itbusinessedge.com","HTTPSConnectionPool(host='jobs.itbusinessedge.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0440850>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"mail-146-67.itbusinessedge.com","HTTPSConnectionPool(host='mail-146-67.itbusinessedge.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd053ae80>, 'Connection to mail-146-67.itbusinessedge.com timed out. (connect timeout=10)'))"
"mail-146-68.itbusinessedge.com","HTTPSConnectionPool(host='mail-146-68.itbusinessedge.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0440550>, 'Connection to mail-146-68.itbusinessedge.com timed out. (connect timeout=10)'))"
"mail-146-69.itbusinessedge.com","HTTPSConnectionPool(host='mail-146-69.itbusinessedge.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0440c40>, 'Connection to mail-146-69.itbusinessedge.com timed out. (connect timeout=10)'))"
"mail-146-70.itbusinessedge.com","HTTPSConnectionPool(host='mail-146-70.itbusinessedge.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0438c70>, 'Connection to mail-146-70.itbusinessedge.com timed out. (connect timeout=10)'))"
"mail-146-71.itbusinessedge.com","HTTPSConnectionPool(host='mail-146-71.itbusinessedge.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04c6d90>, 'Connection to mail-146-71.itbusinessedge.com timed out. (connect timeout=10)'))"
"mail-146-72.itbusinessedge.com","HTTPSConnectionPool(host='mail-146-72.itbusinessedge.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043e280>, 'Connection to mail-146-72.itbusinessedge.com timed out. (connect timeout=10)'))"
"mail-146-73.itbusinessedge.com","HTTPSConnectionPool(host='mail-146-73.itbusinessedge.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043ebe0>, 'Connection to mail-146-73.itbusinessedge.com timed out. (connect timeout=10)'))"
"mail-146-74.itbusinessedge.com","HTTPSConnectionPool(host='mail-146-74.itbusinessedge.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd044b220>, 'Connection to mail-146-74.itbusinessedge.com timed out. (connect timeout=10)'))"
"mail-146-75.itbusinessedge.com","HTTPSConnectionPool(host='mail-146-75.itbusinessedge.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043a970>, 'Connection to mail-146-75.itbusinessedge.com timed out. (connect timeout=10)'))"
"mail-146-90.itbusinessedge.com","HTTPSConnectionPool(host='mail-146-90.itbusinessedge.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd044b160>, 'Connection to mail-146-90.itbusinessedge.com timed out. (connect timeout=10)'))"
"_b4ad2c9ad89c6f50e35feab5f543bee7.mobile.itbusinessedge.com","HTTPSConnectionPool(host='_b4ad2c9ad89c6f50e35feab5f543bee7.mobile.itbusinessedge.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043ee80>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"mt.itbusinessedge.com","HTTPSConnectionPool(host='mt.itbusinessedge.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043e220>, 'Connection to mt.itbusinessedge.com timed out. (connect timeout=10)'))"
"track.news.itbusinessedge.com","HTTPSConnectionPool(host='track.news.itbusinessedge.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043e970>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"nl.itbusinessedge.com","HTTPSConnectionPool(host='nl.itbusinessedge.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0438b80>, 'Connection to nl.itbusinessedge.com timed out. (connect timeout=10)'))"
"mail02.nl.itbusinessedge.com","HTTPSConnectionPool(host='mail02.nl.itbusinessedge.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04389a0>, 'Connection to mail02.nl.itbusinessedge.com timed out. (connect timeout=10)'))"
"nt.itbusinessedge.com","HTTPSConnectionPool(host='nt.itbusinessedge.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0440880>, 'Connection to nt.itbusinessedge.com timed out. (connect timeout=10)'))"
"origin321-mobile.itbusinessedge.com","HTTPSConnectionPool(host='origin321-mobile.itbusinessedge.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043afd0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"origin321-www.itbusinessedge.com","HTTPSConnectionPool(host='origin321-www.itbusinessedge.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043a400>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"partners.itbusinessedge.com","HTTPSConnectionPool(host='partners.itbusinessedge.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0440f40>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"track.promo.itbusinessedge.com","HTTPSConnectionPool(host='track.promo.itbusinessedge.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0438ca0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"resources.itbusinessedge.com","HTTPSConnectionPool(host='resources.itbusinessedge.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04c61c0>, 'Connection to resources.itbusinessedge.com timed out. (connect timeout=10)'))"
"sp.itbusinessedge.com","HTTPSConnectionPool(host='sp.itbusinessedge.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043ec40>, 'Connection to sp.itbusinessedge.com timed out. (connect timeout=10)'))"
"t.itbusinessedge.com","HTTPSConnectionPool(host='t.itbusinessedge.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd044b0a0>, 'Connection to t.itbusinessedge.com timed out. (connect timeout=10)'))"
"ww2.itbusinessedge.com","404 response"
"_cead6c5e1da34d08cea19bb892e6c216.www.itbusinessedge.com","HTTPSConnectionPool(host='_cead6c5e1da34d08cea19bb892e6c216.www.itbusinessedge.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd044b1f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"34404854.enterprisenetworkingplanet.com","404 response"
"assetform.enterprisenetworkingplanet.com","HTTPSConnectionPool(host='assetform.enterprisenetworkingplanet.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd044b970>, 'Connection to assetform.enterprisenetworkingplanet.com timed out. (connect timeout=10)'))"
"downloads.enterprisenetworkingplanet.com","HTTPSConnectionPool(host='downloads.enterprisenetworkingplanet.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043a490>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"forums.enterprisenetworkingplanet.com","HTTPSConnectionPool(host='forums.enterprisenetworkingplanet.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043a790>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"local.enterprisenetworkingplanet.com","HTTPSConnectionPool(host='local.enterprisenetworkingplanet.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043a2b0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"origin321-mobile.enterprisenetworkingplanet.com","HTTPSConnectionPool(host='origin321-mobile.enterprisenetworkingplanet.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043e0a0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"origin321-www.enterprisenetworkingplanet.com","HTTPSConnectionPool(host='origin321-www.enterprisenetworkingplanet.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04c6940>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"products.enterprisenetworkingplanet.com","HTTPSConnectionPool(host='products.enterprisenetworkingplanet.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04389d0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"resources.enterprisenetworkingplanet.com","HTTPSConnectionPool(host='resources.enterprisenetworkingplanet.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0438d60>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"t.enterprisenetworkingplanet.com","HTTPSConnectionPool(host='t.enterprisenetworkingplanet.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0440e50>, 'Connection to t.enterprisenetworkingplanet.com timed out. (connect timeout=10)'))"
"ww2.enterprisenetworkingplanet.com","404 response"
"assetform.datamation.com","HTTPSConnectionPool(host='assetform.datamation.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0438be0>, 'Connection to assetform.datamation.com timed out. (connect timeout=10)'))"
"blog.datamation.com","HTTPSConnectionPool(host='blog.datamation.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0438a90>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"it-jobs.datamation.com","HTTPSConnectionPool(host='it-jobs.datamation.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043e8e0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"itchannel.datamation.com","HTTPSConnectionPool(host='itchannel.datamation.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043efd0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"origin123-www.datamation.com","HTTPSConnectionPool(host='origin123-www.datamation.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0438fd0>, 'Connection to origin123-www.datamation.com timed out. (connect timeout=10)'))"
"origin321-mobile.datamation.com","HTTPSConnectionPool(host='origin321-mobile.datamation.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd044bd30>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"origin321-www.datamation.com","HTTPSConnectionPool(host='origin321-www.datamation.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd044bd30>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"products.datamation.com","HTTPSConnectionPool(host='products.datamation.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043ee80>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"www.products.datamation.com","HTTPSConnectionPool(host='www.products.datamation.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04c6520>, 'Connection to www.products.datamation.com timed out. (connect timeout=10)'))"
"resources.datamation.com","HTTPSConnectionPool(host='resources.datamation.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04387f0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"solutions.datamation.com","HTTPSConnectionPool(host='solutions.datamation.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0440670>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"t.datamation.com","HTTPSConnectionPool(host='t.datamation.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04405e0>, 'Connection to t.datamation.com timed out. (connect timeout=10)'))"
"training.datamation.com","HTTPSConnectionPool(host='training.datamation.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0431790>, 'Connection to training.datamation.com timed out. (connect timeout=10)'))"
"ww2.datamation.com","404 response"
"34406679.infostor.com","404 response"
"assetform.infostor.com","HTTPSConnectionPool(host='assetform.infostor.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0431880>, 'Connection to assetform.infostor.com timed out. (connect timeout=10)'))"
"decisiontree.infostor.com","HTTPSConnectionPool(host='decisiontree.infostor.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04315b0>, 'Connection to decisiontree.infostor.com timed out. (connect timeout=10)'))"
"origin321-mobile.infostor.com","HTTPSConnectionPool(host='origin321-mobile.infostor.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0438070>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"quicksearch.infostor.com","HTTPSConnectionPool(host='quicksearch.infostor.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0438160>, 'Connection to quicksearch.infostor.com timed out. (connect timeout=10)'))"
"resources.infostor.com","HTTPSConnectionPool(host='resources.infostor.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043e670>, 'Connection to resources.infostor.com timed out. (connect timeout=10)'))"
"solutions.infostor.com","HTTPSConnectionPool(host='solutions.infostor.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043e820>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"ww2.infostor.com","404 response"
"itchannelplanet.com","HTTPSConnectionPool(host='www.www.itchannelplanet.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043a580>, 'Connection to www.www.itchannelplanet.com timed out. (connect timeout=10)'))"
"assetform.itchannelplanet.com","HTTPSConnectionPool(host='assetform.itchannelplanet.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043ad60>, 'Connection to assetform.itchannelplanet.com timed out. (connect timeout=10)'))"
"blog.itchannelplanet.com","HTTPSConnectionPool(host='www.blog.itchannelplanet.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0431df0>, 'Connection to www.blog.itchannelplanet.com timed out. (connect timeout=10)'))"
"origin321-www.itchannelplanet.com","HTTPSConnectionPool(host='origin321-www.itchannelplanet.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0431760>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"ww2.itchannelplanet.com","404 response"
"www.itchannelplanet.com","HTTPSConnectionPool(host='www.www.itchannelplanet.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd049b9d0>, 'Connection to www.www.itchannelplanet.com timed out. (connect timeout=10)'))"
"migrationexpertzone.com","HTTPSConnectionPool(host='migrationexpertzone.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043ec10>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"assetform.migrationexpertzone.com","HTTPSConnectionPool(host='assetform.migrationexpertzone.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043e970>, 'Connection to assetform.migrationexpertzone.com timed out. (connect timeout=10)'))"
"dev.migrationexpertzone.com","HTTPSConnectionPool(host='dev.migrationexpertzone.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0438130>, 'Connection to dev.migrationexpertzone.com timed out. (connect timeout=10)'))"
"m.migrationexpertzone.com","HTTPSConnectionPool(host='m.migrationexpertzone.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04388b0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"mobile.migrationexpertzone.com","HTTPSConnectionPool(host='mobile.migrationexpertzone.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0440c40>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"www.migrationexpertzone.com","HTTPSConnectionPool(host='www.migrationexpertzone.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0431e50>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"assetform.jguru.com","HTTPSConnectionPool(host='assetform.jguru.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0438cd0>, 'Connection to assetform.jguru.com timed out. (connect timeout=10)'))"
"communities.jguru.com","HTTPSConnectionPool(host='communities.jguru.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043e790>, 'Connection to communities.jguru.com timed out. (connect timeout=10)'))"
"mail.jguru.com","HTTPSConnectionPool(host='mail.jguru.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd049bd30>, 'Connection to mail.jguru.com timed out. (connect timeout=10)'))"
"seminars.jguru.com","HTTPSConnectionPool(host='seminars.jguru.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043ae20>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"ww2.jguru.com","404 response"
"activebizpro.com","HTTPSConnectionPool(host='activebizpro.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0438ca0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
"activeitpro.asia","HTTPSConnectionPool(host='activeitpro.asia', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0438e50>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
"it-papers.com","HTTPSConnectionPool(host='it-papers.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0438580>, 'Connection to it-papers.com timed out. (connect timeout=10)'))"
"www.it-papers.com","HTTPSConnectionPool(host='www.it-papers.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd044b0d0>, 'Connection to www.it-papers.com timed out. (connect timeout=10)'))"
"activeitpro.sg","HTTPSConnectionPool(host='activeitpro.sg', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0431f40>, 'Connection to activeitpro.sg timed out. (connect timeout=10)'))"
"m.activeitpro.sg","HTTPSConnectionPool(host='m.activeitpro.sg', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0431fd0>, 'Connection to m.activeitpro.sg timed out. (connect timeout=10)'))"
"www.activeitpro.sg","HTTPSConnectionPool(host='www.activeitpro.sg', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043a970>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"activetechpro.asia","HTTPSConnectionPool(host='activetechpro.asia', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd049b550>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
"activebizpros.com.cn","HTTPSConnectionPool(host='activebizpros.com.cn', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd049bdf0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
"activeitpro.com.sg","HTTPSConnectionPool(host='activeitpro.com.sg', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd049bcd0>, 'Connection to activeitpro.com.sg timed out. (connect timeout=10)'))"
"m.activeitpro.com.sg","HTTPSConnectionPool(host='m.activeitpro.com.sg', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043e460>, 'Connection to m.activeitpro.com.sg timed out. (connect timeout=10)'))"
"www.activeitpro.com.sg","HTTPSConnectionPool(host='www.activeitpro.com.sg', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043e970>, 'Connection to www.activeitpro.com.sg timed out. (connect timeout=10)'))"
"activeitpro.com.au","HTTPSConnectionPool(host='activeitpro.com.au', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04380d0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
"australiandeveloper.com.au","HTTPSConnectionPool(host='australiandeveloper.com.au', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0438670>, 'Connection to australiandeveloper.com.au timed out. (connect timeout=10)'))"
"admcms.australiandeveloper.com.au","HTTPSConnectionPool(host='admcms.australiandeveloper.com.au', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0440310>, 'Connection to admcms.australiandeveloper.com.au timed out. (connect timeout=10)'))"
"prvcms.australiandeveloper.com.au","HTTPSConnectionPool(host='prvcms.australiandeveloper.com.au', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04de2b0>, 'Connection to prvcms.australiandeveloper.com.au timed out. (connect timeout=10)'))"
"www.australiandeveloper.com.au","HTTPSConnectionPool(host='www.australiandeveloper.com.au', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0438430>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"065d3fe9bb53baace386bf32c7eaaeb5.techproresearch.com","400 response"
"\337.techproresearch.com","HTTPSConnectionPool(host='%5c337.techproresearch.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04384c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"ci.cache.techproresearch.com","HTTPSConnectionPool(host='ci.cache.techproresearch.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0438d00>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"cdn-origin01.techproresearch.com","HTTPSConnectionPool(host='cdn-origin01.techproresearch.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0438130>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"cms.techproresearch.com","HTTPSConnectionPool(host='cms.techproresearch.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0438d30>, 'Connection to cms.techproresearch.com timed out. (connect timeout=10)'))"
"ct-dev.techproresearch.com","HTTPSConnectionPool(host='ct-dev.techproresearch.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043ed00>, 'Connection to ct-dev.techproresearch.com timed out. (connect timeout=10)'))"
"ct-stage.techproresearch.com","HTTPSConnectionPool(host='ct-stage.techproresearch.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043ef70>, 'Connection to ct-stage.techproresearch.com timed out. (connect timeout=10)'))"
"ct.techproresearch.com","HTTPSConnectionPool(host='ct.techproresearch.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04407c0>, 'Connection to ct.techproresearch.com timed out. (connect timeout=10)'))"
"debug-origin.techproresearch.com","HTTPSConnectionPool(host='debug-origin.techproresearch.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04313d0>, 'Connection to debug-origin.techproresearch.com timed out. (connect timeout=10)'))"
"deco.techproresearch.com","HTTPSConnectionPool(host='deco.techproresearch.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0431af0>, 'Connection to deco.techproresearch.com timed out. (connect timeout=10)'))"
"\052.deco.techproresearch.com","HTTPSConnectionPool(host='%5c052.deco.techproresearch.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd044bb80>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"dev-help.techproresearch.com","HTTPSConnectionPool(host='dev-help.techproresearch.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd044b250>, 'Connection to dev-help.techproresearch.com timed out. (connect timeout=10)'))"
"\052.dev.fly.techproresearch.com","HTTPSConnectionPool(host='%5c052.dev.fly.techproresearch.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0431df0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"\052.dev.hub.techproresearch.com","HTTPSConnectionPool(host='%5c052.dev.hub.techproresearch.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0431b20>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"utest.hub.techproresearch.com","HTTPSConnectionPool(host='utest.hub.techproresearch.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0431ee0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"internal-origin.techproresearch.com","HTTPSConnectionPool(host='internal-origin.techproresearch.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04c6d30>, 'Connection to internal-origin.techproresearch.com timed out. (connect timeout=10)'))"
"ci.mysql.techproresearch.com","HTTPSConnectionPool(host='ci.mysql.techproresearch.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043eac0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"origin-api.techproresearch.com","HTTPSConnectionPool(host='origin-api.techproresearch.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043edf0>, 'Connection to origin-api.techproresearch.com timed out. (connect timeout=10)'))"
"origin-fly.techproresearch.com","HTTPSConnectionPool(host='origin-fly.techproresearch.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04388b0>, 'Connection to origin-fly.techproresearch.com timed out. (connect timeout=10)'))"
"origin01.techproresearch.com","HTTPSConnectionPool(host='origin01.techproresearch.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04384c0>, 'Connection to origin01.techproresearch.com timed out. (connect timeout=10)'))"
"secure-ci-fly.techproresearch.com","HTTPSConnectionPool(host='secure-ci-fly.techproresearch.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd049bc40>, 'Connection to secure-ci-fly.techproresearch.com timed out. (connect timeout=10)'))"
"ci.solr.techproresearch.com","HTTPSConnectionPool(host='ci.solr.techproresearch.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0438160>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"urs-dev-int.techproresearch.com","HTTPSConnectionPool(host='urs-dev-int.techproresearch.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0438a90>, 'Connection to urs-dev-int.techproresearch.com timed out. (connect timeout=10)'))"
"urs-dev.techproresearch.com","HTTPSConnectionPool(host='urs-dev.techproresearch.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043e8b0>, 'Connection to urs-dev.techproresearch.com timed out. (connect timeout=10)'))"
"urs-int.techproresearch.com","HTTPSConnectionPool(host='urs-int.techproresearch.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043ed60>, 'Connection to urs-int.techproresearch.com timed out. (connect timeout=10)'))"
"urs-qa-int.techproresearch.com","HTTPSConnectionPool(host='urs-qa-int.techproresearch.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0440100>, 'Connection to urs-qa-int.techproresearch.com timed out. (connect timeout=10)'))"
"urs-qa.techproresearch.com","HTTPSConnectionPool(host='urs-qa.techproresearch.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0431f70>, 'Connection to urs-qa.techproresearch.com timed out. (connect timeout=10)'))"
"urs.techproresearch.com","HTTPSConnectionPool(host='urs.techproresearch.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04313d0>, 'Connection to urs.techproresearch.com timed out. (connect timeout=10)'))"
"utest-cms.techproresearch.com","HTTPSConnectionPool(host='utest-cms.techproresearch.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd044bc70>, 'Connection to utest-cms.techproresearch.com timed out. (connect timeout=10)'))"
"varnish-api.techproresearch.com","HTTPSConnectionPool(host='varnish-api.techproresearch.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd044bc40>, 'Connection to varnish-api.techproresearch.com timed out. (connect timeout=10)'))"
"wpt.techproresearch.com","HTTPSConnectionPool(host='wpt.techproresearch.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0431820>, 'Connection to wpt.techproresearch.com timed out. (connect timeout=10)'))"
"techrepublic.fr","HTTPSConnectionPool(host='techrepublic.fr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043e070>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"www.techrepublic.fr","HTTPSConnectionPool(host='www.techrepublic.fr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0440550>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"techepublic.com","HTTPSConnectionPool(host='techepublic.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04380d0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
"techrepublic.com.au","HTTPSConnectionPool(host='techrepublic.com.au', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0438850>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"admcms.techrepublic.com.au","HTTPSConnectionPool(host='admcms.techrepublic.com.au', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0438a30>, 'Connection to admcms.techrepublic.com.au timed out. (connect timeout=10)'))"
"prvcms.techrepublic.com.au","HTTPSConnectionPool(host='prvcms.techrepublic.com.au', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043a520>, 'Connection to prvcms.techrepublic.com.au timed out. (connect timeout=10)'))"
"www.techrepublic.com.au","HTTPSConnectionPool(host='www.techrepublic.com.au', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043abb0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"techrepublic.info","HTTPSConnectionPool(host='techrepublic.info', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0438970>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"www.techrepublic.info","HTTPSConnectionPool(host='www.techrepublic.info', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04387f0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"techrepublic.ca","HTTPSConnectionPool(host='techrepublic.ca', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0440910>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
"techrepublic.org","HTTPSConnectionPool(host='techrepublic.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0440cd0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"www.techrepublic.org","HTTPSConnectionPool(host='www.techrepublic.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04310a0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"techrepublic.jobs","HTTPSConnectionPool(host='techrepublic.jobs', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043ee80>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"www.techrepublic.jobs","HTTPSConnectionPool(host='www.techrepublic.jobs', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043e5e0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"techrepublic.xn--fiqs8s","HTTPSConnectionPool(host='techrepublic.xn--fiqs8s', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd044b130>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
"techrepublic.me","HTTPSConnectionPool(host='techrepublic.me', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd044b220>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"www.techrepublic.me","HTTPSConnectionPool(host='www.techrepublic.me', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043aeb0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"techrepublic.tel","HTTPSConnectionPool(host='techrepublic.tel', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043e5e0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"www.techrepublic.tel","HTTPSConnectionPool(host='www.techrepublic.tel', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0431040>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"techresearchpro.com","HTTPSConnectionPool(host='techresearchpro.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04316d0>, 'Connection to techresearchpro.com timed out. (connect timeout=10)'))"
"www.techresearchpro.com","HTTPSConnectionPool(host='www.techresearchpro.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04c6fd0>, 'Connection to www.techresearchpro.com timed out. (connect timeout=10)'))"
"trstatic.com","HTTPSConnectionPool(host='trstatic.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0438a00>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
"\052.trstatic.com","HTTPSConnectionPool(host='%5c052.trstatic.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0438a90>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"virusthreatcenter.com","HTTPSConnectionPool(host='virusthreatcenter.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0438be0>, 'Connection to virusthreatcenter.com timed out. (connect timeout=10)'))"
"hh.virusthreatcenter.com","HTTPSConnectionPool(host='hh.virusthreatcenter.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd049b880>, 'Connection to hh.virusthreatcenter.com timed out. (connect timeout=10)'))"
"\052.hh.virusthreatcenter.com","HTTPSConnectionPool(host='%5c052.hh.virusthreatcenter.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043a340>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"\052.rbpreview.virusthreatcenter.com","HTTPSConnectionPool(host='%5c052.rbpreview.virusthreatcenter.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043a280>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"si.virusthreatcenter.com","HTTPSConnectionPool(host='si.virusthreatcenter.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043a1f0>, 'Connection to si.virusthreatcenter.com timed out. (connect timeout=10)'))"
"\052.si.virusthreatcenter.com","HTTPSConnectionPool(host='%5c052.si.virusthreatcenter.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043ac70>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"\052.tron2.virusthreatcenter.com","HTTPSConnectionPool(host='%5c052.tron2.virusthreatcenter.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043af10>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"\052.tron5.virusthreatcenter.com","HTTPSConnectionPool(host='%5c052.tron5.virusthreatcenter.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043aaf0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"\052.uat.virusthreatcenter.com","HTTPSConnectionPool(host='%5c052.uat.virusthreatcenter.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043ae50>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"\052.uat2.virusthreatcenter.com","HTTPSConnectionPool(host='%5c052.uat2.virusthreatcenter.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043a1c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"uat3.virusthreatcenter.com","HTTPSConnectionPool(host='uat3.virusthreatcenter.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043ad00>, 'Connection to uat3.virusthreatcenter.com timed out. (connect timeout=10)'))"
"\052.uat3.virusthreatcenter.com","HTTPSConnectionPool(host='%5c052.uat3.virusthreatcenter.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0438d60>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"\052.uat5.virusthreatcenter.com","HTTPSConnectionPool(host='%5c052.uat5.virusthreatcenter.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0438ee0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"ursdev.virusthreatcenter.com","HTTPSConnectionPool(host='ursdev.virusthreatcenter.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04381c0>, 'Connection to ursdev.virusthreatcenter.com timed out. (connect timeout=10)'))"
"\052.ursdev.virusthreatcenter.com","HTTPSConnectionPool(host='%5c052.ursdev.virusthreatcenter.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04387f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"ursqa.virusthreatcenter.com","HTTPSConnectionPool(host='ursqa.virusthreatcenter.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0438af0>, 'Connection to ursqa.virusthreatcenter.com timed out. (connect timeout=10)'))"
"\052.ursqa.virusthreatcenter.com","HTTPSConnectionPool(host='%5c052.ursqa.virusthreatcenter.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04310d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"www.virusthreatcenter.com","HTTPSConnectionPool(host='www.virusthreatcenter.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0431c70>, 'Connection to www.virusthreatcenter.com timed out. (connect timeout=10)'))"
"xsite.virusthreatcenter.com","HTTPSConnectionPool(host='xsite.virusthreatcenter.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0431a00>, 'Connection to xsite.virusthreatcenter.com timed out. (connect timeout=10)'))"
"\052.xsite.virusthreatcenter.com","HTTPSConnectionPool(host='%5c052.xsite.virusthreatcenter.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043ec70>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"wwwtechrepublic.com","HTTPSConnectionPool(host='wwwtechrepublic.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043e760>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
"34406668.flashkit.com","404 response"
"_14663898941515cad490ecf853ecfda0.flashkit.com","HTTPSConnectionPool(host='_14663898941515cad490ecf853ecfda0.flashkit.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0431850>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"assetform.flashkit.com","HTTPSConnectionPool(host='assetform.flashkit.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04311c0>, 'Connection to assetform.flashkit.com timed out. (connect timeout=10)'))"
"dev.board.flashkit.com","HTTPSConnectionPool(host='dev.board.flashkit.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0431130>, 'Connection to dev.board.flashkit.com timed out. (connect timeout=10)'))"
"classifieds.flashkit.com","HTTPSConnectionPool(host='www.classifieds.flashkit.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0431490>, 'Connection to www.classifieds.flashkit.com timed out. (connect timeout=10)'))"
"downloads.flashkit.com","HTTPSConnectionPool(host='downloads.flashkit.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0440fd0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"images.flashkit.com","HTTPSConnectionPool(host='images.flashkit.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04380d0>, 'Connection to images.flashkit.com timed out. (connect timeout=10)'))"
"images2.flashkit.com","HTTPSConnectionPool(host='images2.flashkit.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0438ee0>, 'Connection to images2.flashkit.com timed out. (connect timeout=10)'))"
"origin321-www.flashkit.com","HTTPSConnectionPool(host='www.origin321-www.flashkit.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043aa60>, 'Connection to www.origin321-www.flashkit.com timed out. (connect timeout=10)'))"
"pro.flashkit.com","HTTPSConnectionPool(host='www.pro.flashkit.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd042da30>, 'Connection to www.pro.flashkit.com timed out. (connect timeout=10)'))"
"submissions.flashkit.com","HTTPSConnectionPool(host='www.submissions.flashkit.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0438cd0>, 'Connection to www.submissions.flashkit.com timed out. (connect timeout=10)'))"
"34404871.codeguru.com","404 response"
"_bbca0754bdcb22d28aebbe54e013b66b.codeguru.com","HTTPSConnectionPool(host='_bbca0754bdcb22d28aebbe54e013b66b.codeguru.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04406a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"assetform.codeguru.com","403 response"
"blog.codeguru.com","403 response"
"codewise.codeguru.com","403 response"
"extra.codeguru.com","403 response"
"dev.forums.codeguru.com","HTTPSConnectionPool(host='dev.forums.codeguru.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0440310>, 'Connection to dev.forums.codeguru.com timed out. (connect timeout=10)'))"
"loghost.codeguru.com","403 response"
"mobile.codeguru.com","403 response"
"_9e05c53962798a80e7609040574d3f56.mobile.codeguru.com","HTTPSConnectionPool(host='_9e05c53962798a80e7609040574d3f56.mobile.codeguru.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04389a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"origin321-www.codeguru.com","HTTPSConnectionPool(host='origin321-www.codeguru.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04387f0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"training.codeguru.com","403 response"
"waldorf.codeguru.com","HTTPSConnectionPool(host='waldorf.codeguru.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0431460>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"_3d7e77c74b6f93e7d3bd050add42ff66.www.codeguru.com","HTTPSConnectionPool(host='_3d7e77c74b6f93e7d3bd050add42ff66.www.codeguru.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04319d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"34406611.sharkyforums.com","404 response"
"_dc4ec024261cfd461a785358c4da4764.sharkyforums.com","HTTPSConnectionPool(host='_dc4ec024261cfd461a785358c4da4764.sharkyforums.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0431940>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"dnwjpfvzfcf2xlem53udqdvq4v7pzikx._domainkey.sharkyforums.com","HTTPSConnectionPool(host='dnwjpfvzfcf2xlem53udqdvq4v7pzikx._domainkey.sharkyforums.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0431160>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"gcnialwiomsm32fwtbqbpwmsxslihkkq._domainkey.sharkyforums.com","HTTPSConnectionPool(host='gcnialwiomsm32fwtbqbpwmsxslihkkq._domainkey.sharkyforums.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0431f40>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"oxgrvtn3rxkjbfayjjklq5zqhnx6xlfw._domainkey.sharkyforums.com","HTTPSConnectionPool(host='oxgrvtn3rxkjbfayjjklq5zqhnx6xlfw._domainkey.sharkyforums.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04312b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"dev.www.sharkyforums.com","HTTPSConnectionPool(host='dev.www.sharkyforums.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0431760>, 'Connection to dev.www.sharkyforums.com timed out. (connect timeout=10)'))"
"34406618.justlinux.com","404 response"
"_9a7445f68aa0ae0529f7548b22ab651a.justlinux.com","HTTPSConnectionPool(host='_9a7445f68aa0ae0529f7548b22ab651a.justlinux.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043e880>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"dev.forums.justlinux.com","HTTPSConnectionPool(host='dev.forums.justlinux.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd053a670>, 'Connection to dev.forums.justlinux.com timed out. (connect timeout=10)'))"
"15seconds.webopedia.com","HTTPSConnectionPool(host='15seconds.webopedia.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0440a30>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"34381324.webopedia.com","404 response"
"80211-planet.webopedia.com","HTTPSConnectionPool(host='80211-planet.webopedia.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0431700>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"aol.webopedia.com","HTTPSConnectionPool(host='aol.webopedia.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04314f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"applanet.webopedia.com","HTTPSConnectionPool(host='applanet.webopedia.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0431c40>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"assetform.webopedia.com","HTTPSConnectionPool(host='assetform.webopedia.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0431ac0>, 'Connection to assetform.webopedia.com timed out. (connect timeout=10)'))"
"bigyellow.webopedia.com","HTTPSConnectionPool(host='bigyellow.webopedia.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043ab20>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"clec.webopedia.com","HTTPSConnectionPool(host='clec.webopedia.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043a490>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"dev-www.webopedia.com","HTTPSConnectionPool(host='dev-www.webopedia.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0438f10>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"drmwatch.webopedia.com","HTTPSConnectionPool(host='drmwatch.webopedia.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04385b0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"e-comm.webopedia.com","HTTPSConnectionPool(host='e-comm.webopedia.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0438580>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"ecrmguide.webopedia.com","HTTPSConnectionPool(host='ecrmguide.webopedia.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0438850>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"enterprisestorageforum.webopedia.com","HTTPSConnectionPool(host='enterprisestorageforum.webopedia.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043a910>, 'Connection to enterprisestorageforum.webopedia.com timed out. (connect timeout=10)'))"
"esecurity.webopedia.com","HTTPSConnectionPool(host='esecurity.webopedia.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043ac70>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"ewebnews.webopedia.com","HTTPSConnectionPool(host='ewebnews.webopedia.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0431ca0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"inews.webopedia.com","HTTPSConnectionPool(host='www.inews.webopedia.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd053a400>, 'Connection to www.inews.webopedia.com timed out. (connect timeout=10)'))"
"insideid.webopedia.com","HTTPSConnectionPool(host='insideid.webopedia.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043e580>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"isp.webopedia.com","HTTPSConnectionPool(host='isp.webopedia.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd044b9a0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"itmanagement.webopedia.com","HTTPSConnectionPool(host='itmanagement.webopedia.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd049b550>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"jobs.webopedia.com","HTTPSConnectionPool(host='jobs.webopedia.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd053aac0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"m.webopedia.com","HTTPSConnectionPool(host='m.webopedia.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd053a8e0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"networking.webopedia.com","HTTPSConnectionPool(host='networking.webopedia.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04317f0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"networkstorageforum.webopedia.com","HTTPSConnectionPool(host='networkstorageforum.webopedia.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0431a00>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"new.webopedia.com","HTTPSConnectionPool(host='new.webopedia.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043a730>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"origin.webopedia.com","HTTPSConnectionPool(host='origin.webopedia.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0438ca0>, 'Connection to origin.webopedia.com timed out. (connect timeout=10)'))"
"origin321-www.webopedia.com","HTTPSConnectionPool(host='origin321-www.webopedia.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0438430>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"practicallynetworked.webopedia.com","HTTPSConnectionPool(host='practicallynetworked.webopedia.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0438b80>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"sbc.webopedia.com","HTTPSConnectionPool(host='sbc.webopedia.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0431100>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"search.webopedia.com","HTTPSConnectionPool(host='search.webopedia.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0431850>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"serverwatch.webopedia.com","HTTPSConnectionPool(host='serverwatch.webopedia.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0431e50>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"systems.webopedia.com","HTTPSConnectionPool(host='systems.webopedia.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04dea00>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"isp.thelist.webopedia.com","HTTPSConnectionPool(host='isp.thelist.webopedia.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043ec40>, 'Connection to isp.thelist.webopedia.com timed out. (connect timeout=10)'))"
"webhosts.thelist.webopedia.com","HTTPSConnectionPool(host='webhosts.thelist.webopedia.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043eeb0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"thetech.webopedia.com","HTTPSConnectionPool(host='thetech.webopedia.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043acd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"uwb.webopedia.com","HTTPSConnectionPool(host='uwb.webopedia.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043a7f0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"voipplanet.webopedia.com","HTTPSConnectionPool(host='voipplanet.webopedia.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043a0a0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"wap.webopedia.com","HTTPSConnectionPool(host='wap.webopedia.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043a070>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"webvideouniverse.webopedia.com","HTTPSConnectionPool(host='webvideouniverse.webopedia.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043a2b0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"wi-fiplanet.webopedia.com","HTTPSConnectionPool(host='wi-fiplanet.webopedia.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043e970>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"winplanet.webopedia.com","HTTPSConnectionPool(host='winplanet.webopedia.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043e100>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"ww2.webopedia.com","404 response"
"_acme-challenge.www.webopedia.com","HTTPSConnectionPool(host='_acme-challenge.www.webopedia.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04de760>, 'Connection to _acme-challenge.www.webopedia.com timed out. (connect timeout=10)'))"
"34404861.channelinsider.com","404 response"
"assetform.channelinsider.com","403 response"
"blog.channelinsider.com","HTTPSConnectionPool(host='blog.channelinsider.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04401f0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"blogs.channelinsider.com","HTTPSConnectionPool(host='blogs.channelinsider.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0431190>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"buyersguide.channelinsider.com","HTTPSConnectionPool(host='buyersguide.channelinsider.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0431520>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"ct.channelinsider.com","HTTPSConnectionPool(host='ct.channelinsider.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04389a0>, 'Connection to ct.channelinsider.com timed out. (connect timeout=10)'))"
"m.channelinsider.com","403 response"
"www.m.channelinsider.com","403 response"
"mobile.channelinsider.com","403 response"
"_835d3304bdf38723622f39cf9bc99bdb.mobile.channelinsider.com","HTTPSConnectionPool(host='_835d3304bdf38723622f39cf9bc99bdb.mobile.channelinsider.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0440550>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"www.mobile.channelinsider.com","403 response"
"mobilenew.channelinsider.com","HTTPSConnectionPool(host='mobilenew.channelinsider.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0440640>, 'Connection to mobilenew.channelinsider.com timed out. (connect timeout=10)'))"
"origin123-www.channelinsider.com","HTTPSConnectionPool(host='origin123-www.channelinsider.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04de0d0>, 'Connection to origin123-www.channelinsider.com timed out. (connect timeout=10)'))"
"origin321-mobile.channelinsider.com","HTTPSConnectionPool(host='origin321-mobile.channelinsider.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd053a9d0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"origin321-www.channelinsider.com","HTTPSConnectionPool(host='origin321-www.channelinsider.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043e100>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"response.channelinsider.com","HTTPSConnectionPool(host='response.channelinsider.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043adf0>, 'Connection to response.channelinsider.com timed out. (connect timeout=10)'))"
"t.channelinsider.com","HTTPSConnectionPool(host='t.channelinsider.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043a340>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"ww2.channelinsider.com","404 response"
"_96844ca0b6ac72251f96486507f2c34a.www.channelinsider.com","HTTPSConnectionPool(host='_96844ca0b6ac72251f96486507f2c34a.www.channelinsider.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043a220>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"_acme-challenge.www.channelinsider.com","HTTPSConnectionPool(host='_acme-challenge.www.channelinsider.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043e7c0>, 'Connection to _acme-challenge.www.channelinsider.com timed out. (connect timeout=10)'))"
"assetform.enterprisemobiletoday.com","HTTPSConnectionPool(host='assetform.enterprisemobiletoday.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0440100>, 'Connection to assetform.enterprisemobiletoday.com timed out. (connect timeout=10)'))"
"origin321-www.enterprisemobiletoday.com","HTTPSConnectionPool(host='origin321-www.enterprisemobiletoday.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0431250>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"products.enterprisemobiletoday.com","HTTPSConnectionPool(host='products.enterprisemobiletoday.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043a2e0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"resources.enterprisemobiletoday.com","HTTPSConnectionPool(host='resources.enterprisemobiletoday.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043abe0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"ww2.enterprisemobiletoday.com","404 response"
"34404866.enterprisestorageforum.com","404 response"
"assetform.enterprisestorageforum.com","HTTPSConnectionPool(host='assetform.enterprisestorageforum.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04de3d0>, 'Connection to assetform.enterprisestorageforum.com timed out. (connect timeout=10)'))"
"origin.enterprisestorageforum.com","HTTPSConnectionPool(host='origin.enterprisestorageforum.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043a340>, 'Connection to origin.enterprisestorageforum.com timed out. (connect timeout=10)'))"
"origin321-mobile.enterprisestorageforum.com","HTTPSConnectionPool(host='origin321-mobile.enterprisestorageforum.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0431c40>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
"origin321-www.enterprisestorageforum.com","HTTPSConnectionPool(host='origin321-www.enterprisestorageforum.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04313d0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"products.enterprisestorageforum.com","HTTPSConnectionPool(host='products.enterprisestorageforum.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0431880>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"resources.enterprisestorageforum.com","HTTPSConnectionPool(host='resources.enterprisestorageforum.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0440250>: Failed to establish a new connection: [Errno 111] Connection refused'))"
"ww2.enterprisestorageforum.com","404 response"
"_28c590a6e1344c10864e5e8bcb9cf62b.www.enterprisestorageforum.com","HTTPSConnectionPool(host='_28c590a6e1344c10864e5e8bcb9cf62b.www.enterprisestorageforum.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0440640>, 'Connection to _28c590a6e1344c10864e5e8bcb9cf62b.www.enterprisestorageforum.com timed out. (connect timeout=10)'))"
"activebizpros.co.uk","HTTPSConnectionPool(host='activebizpros.co.uk', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04de580>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
"activeitpros.co.uk","HTTPSConnectionPool(host='activeitpros.co.uk', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04de730>, 'Connection to activeitpros.co.uk timed out. (connect timeout=10)'))"
"www.activeitpros.co.uk","HTTPSConnectionPool(host='www.activeitpros.co.uk', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043ed30>, 'Connection to www.activeitpros.co.uk timed out. (connect timeout=10)'))"
"activeitpros.com.cn","HTTPSConnectionPool(host='activeitpros.com.cn', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0440100>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
"activebizpro.com.tw","HTTPSConnectionPool(host='activebizpro.com.tw', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04c6280>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
"activetechpro.com","HTTPSConnectionPool(host='activetechpro.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04c6280>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
"activetechpros.cn","HTTPSConnectionPool(host='activetechpros.cn', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04c6280>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
"activetechpros.com.cn","HTTPSConnectionPool(host='activetechpros.com.cn', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04c6280>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
"activeitpros.asia","HTTPSConnectionPool(host='activeitpros.asia', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04c6280>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
"activeitpros.org","HTTPSConnectionPool(host='activeitpros.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04c6280>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
"activeitpros.sg","HTTPSConnectionPool(host='activeitpros.sg', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04c6280>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
"activesmb.com","HTTPSConnectionPool(host='activesmb.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04c6280>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
"activetechpro.com.au","HTTPSConnectionPool(host='activetechpro.com.au', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd04c69d0>, 'Connection to activetechpro.com.au timed out. (connect timeout=10)'))"
"m.activetechpro.com.au","HTTPSConnectionPool(host='m.activetechpro.com.au', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd0431be0>, 'Connection to m.activetechpro.com.au timed out. (connect timeout=10)'))"
"www.activetechpro.com.au","HTTPSConnectionPool(host='www.activetechpro.com.au', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043a310>, 'Connection to www.activetechpro.com.au timed out. (connect timeout=10)'))"
"activetechpro.com.sg","HTTPSConnectionPool(host='activetechpro.com.sg', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1fd043a6a0>, 'Connection to activetechpro.com.sg timed out. (connect timeout=10)'))"
